[2024-09-04T05:29:30.431+0000] {processor.py:186} INFO - Started process (PID=29) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:29:30.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:29:30.437+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:29:30.437+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:29:30.470+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:29:30.467+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 28, in <module>
    python_callable=reddit_pipeline,
NameError: name 'reddit_pipeline' is not defined
[2024-09-04T05:29:30.470+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:29:30.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.072 seconds
[2024-09-04T05:30:00.846+0000] {processor.py:186} INFO - Started process (PID=30) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:30:00.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:30:00.852+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:30:00.851+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:30:00.869+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:30:00.866+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 28, in <module>
    python_callable=reddit_pipeline,
NameError: name 'reddit_pipeline' is not defined
[2024-09-04T05:30:00.869+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:30:00.901+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.069 seconds
[2024-09-04T05:30:31.258+0000] {processor.py:186} INFO - Started process (PID=31) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:30:31.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:30:31.261+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:30:31.260+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:30:31.265+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:30:31.264+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 28, in <module>
    python_callable=reddit_pipeline,
NameError: name 'reddit_pipeline' is not defined
[2024-09-04T05:30:31.265+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:30:31.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.027 seconds
[2024-09-04T05:31:01.695+0000] {processor.py:186} INFO - Started process (PID=32) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:31:01.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:31:01.701+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:31:01.700+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:31:01.714+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:31:01.712+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 28, in <module>
    python_callable=reddit_pipeline,
NameError: name 'reddit_pipeline' is not defined
[2024-09-04T05:31:01.714+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:31:01.730+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.047 seconds
[2024-09-04T05:31:32.106+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:31:32.106+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:31:32.108+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:31:32.108+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:31:32.114+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:31:32.113+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 28, in <module>
    python_callable=reddit_pipeline,
NameError: name 'reddit_pipeline' is not defined
[2024-09-04T05:31:32.115+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:31:32.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.029 seconds
[2024-09-04T05:32:02.488+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:32:02.490+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:32:02.496+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:32:02.495+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:32:02.521+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:32:02.520+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 28, in <module>
    python_callable=reddit_pipeline,
NameError: name 'reddit_pipeline' is not defined
[2024-09-04T05:32:02.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:32:02.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.062 seconds
[2024-09-04T05:32:32.873+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:32:32.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:32:32.878+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:32:32.878+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:32:32.889+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:32:32.887+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 28, in <module>
    python_callable=reddit_pipeline,
NameError: name 'reddit_pipeline' is not defined
[2024-09-04T05:32:32.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:32:32.911+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.068 seconds
[2024-09-04T05:33:03.109+0000] {processor.py:186} INFO - Started process (PID=36) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:33:03.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:33:03.113+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:33:03.112+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:33:03.123+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:33:03.122+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 28, in <module>
    python_callable=reddit_pipeline,
NameError: name 'reddit_pipeline' is not defined
[2024-09-04T05:33:03.124+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:33:03.140+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.040 seconds
[2024-09-04T05:33:33.458+0000] {processor.py:186} INFO - Started process (PID=37) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:33:33.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:33:33.463+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:33:33.462+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:33:33.471+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:33:33.470+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 28, in <module>
    python_callable=reddit_pipeline,
NameError: name 'reddit_pipeline' is not defined
[2024-09-04T05:33:33.472+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:33:33.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.047 seconds
[2024-09-04T05:34:03.941+0000] {processor.py:186} INFO - Started process (PID=38) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:34:03.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:34:03.945+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:34:03.945+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:34:03.956+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:34:03.954+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 28, in <module>
    python_callable=reddit_pipeline,
NameError: name 'reddit_pipeline' is not defined
[2024-09-04T05:34:03.956+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:34:03.976+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.054 seconds
[2024-09-04T05:34:34.373+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:34:34.374+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:34:34.379+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:34:34.378+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:34:34.390+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:34:34.389+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 28, in <module>
    python_callable=reddit_pipeline,
NameError: name 'reddit_pipeline' is not defined
[2024-09-04T05:34:34.391+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:34:34.415+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.057 seconds
[2024-09-04T05:35:04.812+0000] {processor.py:186} INFO - Started process (PID=40) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:35:04.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:35:04.817+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:35:04.816+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:35:04.828+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:35:04.827+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 28, in <module>
    python_callable=reddit_pipeline,
NameError: name 'reddit_pipeline' is not defined
[2024-09-04T05:35:04.828+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:35:04.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.050 seconds
[2024-09-04T05:35:35.275+0000] {processor.py:186} INFO - Started process (PID=41) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:35:35.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:35:35.280+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:35:35.280+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:35:35.292+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:35:35.290+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 28, in <module>
    python_callable=reddit_pipeline,
NameError: name 'reddit_pipeline' is not defined
[2024-09-04T05:35:35.293+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:35:35.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.073 seconds
[2024-09-04T05:36:05.700+0000] {processor.py:186} INFO - Started process (PID=42) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:36:05.701+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:36:05.706+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:36:05.705+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:36:05.718+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:36:05.716+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 28, in <module>
    python_callable=reddit_pipeline,
NameError: name 'reddit_pipeline' is not defined
[2024-09-04T05:36:05.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:36:05.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.072 seconds
[2024-09-04T05:36:33.083+0000] {processor.py:186} INFO - Started process (PID=43) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:36:33.086+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:36:33.089+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:36:33.089+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:36:33.104+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:36:33.102+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 8, in <module>
    from pipelines.reddit_pipeline import  reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 1, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 10, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-09-04T05:36:33.104+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:36:33.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.075 seconds
[2024-09-04T05:36:46.318+0000] {processor.py:186} INFO - Started process (PID=44) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:36:46.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:36:46.325+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:36:46.324+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:36:46.359+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:36:46.340+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import  reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 1, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 10, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-09-04T05:36:46.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:36:46.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.093 seconds
[2024-09-04T05:37:16.795+0000] {processor.py:186} INFO - Started process (PID=45) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:37:16.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:37:16.801+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:37:16.800+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:37:16.813+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:37:16.811+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import  reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 1, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 10, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-09-04T05:37:16.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:37:16.840+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.081 seconds
[2024-09-04T05:37:47.254+0000] {processor.py:186} INFO - Started process (PID=46) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:37:47.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:37:47.261+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:37:47.261+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:37:47.273+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:37:47.271+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import  reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 1, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 10, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-09-04T05:37:47.273+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:37:47.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.080 seconds
[2024-09-04T05:38:17.738+0000] {processor.py:186} INFO - Started process (PID=47) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:38:17.739+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:38:17.744+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:38:17.743+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:38:17.756+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:38:17.754+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import  reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 1, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 10, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-09-04T05:38:17.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:38:17.799+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.071 seconds
[2024-09-04T05:38:48.250+0000] {processor.py:186} INFO - Started process (PID=48) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:38:48.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:38:48.255+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:38:48.254+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:38:48.267+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:38:48.265+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import  reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 1, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 10, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-09-04T05:38:48.268+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:38:48.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.067 seconds
[2024-09-04T05:39:18.644+0000] {processor.py:186} INFO - Started process (PID=49) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:39:18.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:39:18.652+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:39:18.652+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:39:18.669+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:39:18.667+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import  reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 1, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 10, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-09-04T05:39:18.670+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:39:18.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.144 seconds
[2024-09-04T05:39:49.094+0000] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:39:49.096+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddits_dag.py for tasks to queue
[2024-09-04T05:39:49.099+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:39:49.099+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:39:49.112+0000] {logging_mixin.py:190} INFO - [2024-09-04T05:39:49.109+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/reddits_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddits_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import  reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 1, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 10, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-09-04T05:39:49.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddits_dag.py
[2024-09-04T05:39:49.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddits_dag.py took 0.055 seconds
